//dat (type: Date)
//exercise (type -> [])
    // type (type -> string)
    // name (type -> string)
    // duration (type -> number)
    // weight (type -> number)
    // reps (type -> number)
    // sets (type -> number)
    // distance (type -> number)